import { StyleSheet } from 'react-native';

import { C } from './constants';

export const styles = StyleSheet.create({
  flex: { flex: 1 },
  center: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: C.bg,
    gap: 8,
  },
  logo: {
    fontSize: 36,
    fontWeight: '800',
    color: C.primary,
  },
  authContent: {
    flexGrow: 1,
    backgroundColor: C.bg,
    paddingHorizontal: 20,
    justifyContent: 'center',
    gap: 20,
  },
  authHero: {
    backgroundColor: C.primary,
    borderRadius: 28,
    padding: 24,
    gap: 12,
    shadowColor: C.primaryDark,
    shadowOpacity: 0.22,
    shadowRadius: 22,
    shadowOffset: { width: 0, height: 12 },
    elevation: 8,
  },
  authTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  authBrand: {
    color: '#fff',
    fontSize: 18,
    fontWeight: '700',
  },
  authBadge: {
    backgroundColor: 'rgba(255,255,255,0.18)',
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  authBadgeText: {
    color: '#fff',
    fontSize: 11,
    fontWeight: '800',
  },
  authTitle: {
    color: '#fff',
    fontSize: 28,
    fontWeight: '800',
    lineHeight: 34,
  },
  authText: {
    color: 'rgba(255,255,255,0.82)',
    fontSize: 14,
    lineHeight: 21,
  },
  authPreview: {
    marginTop: 10,
    backgroundColor: 'rgba(255,255,255,0.14)',
    borderRadius: 18,
    padding: 14,
    gap: 10,
  },
  previewLineWide: {
    width: '72%',
    height: 10,
    borderRadius: 10,
    backgroundColor: 'rgba(255,255,255,0.72)',
  },
  previewLine: {
    width: '48%',
    height: 8,
    borderRadius: 8,
    backgroundColor: 'rgba(255,255,255,0.36)',
  },
  previewRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  previewDot: {
    width: 26,
    height: 26,
    borderRadius: 10,
    backgroundColor: 'rgba(255,255,255,0.72)',
  },
  previewBar: {
    flex: 1,
    height: 22,
    borderRadius: 12,
    backgroundColor: 'rgba(255,255,255,0.28)',
  },
  authPanel: {
    backgroundColor: C.card,
    borderRadius: 22,
    padding: 18,
    gap: 12,
    borderWidth: 1,
    borderColor: C.border,
    shadowColor: '#000',
    shadowOpacity: 0.06,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 10 },
    elevation: 4,
  },
  authFootnote: {
    color: C.muted,
    fontSize: 12,
    lineHeight: 18,
    textAlign: 'center',
  },
  screenContent: {
    backgroundColor: C.bg,
    paddingHorizontal: 16,
    gap: 16,
  },
  headerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  iconButton: {
    width: 40,
    height: 40,
    borderRadius: 15,
    backgroundColor: C.card,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: C.border,
  },
  iconButtonText: {
    color: C.ink,
    fontSize: 22,
    lineHeight: 24,
    fontWeight: '900',
  },
  pageTitle: {
    fontSize: 24,
    fontWeight: '800',
    color: C.ink,
  },
  hero: {
    backgroundColor: C.primary,
    borderRadius: 28,
    padding: 22,
    gap: 14,
    shadowColor: C.primaryDark,
    shadowOpacity: 0.2,
    shadowRadius: 22,
    shadowOffset: { width: 0, height: 12 },
    elevation: 8,
  },
  heroTopRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
  },
  heroOverline: {
    color: 'rgba(255,255,255,0.72)',
    fontSize: 13,
    fontWeight: '600',
  },
  heroTitle: {
    color: '#fff',
    fontSize: 24,
    fontWeight: '800',
  },
  heroText: {
    color: 'rgba(255,255,255,0.82)',
    fontSize: 14,
    lineHeight: 21,
  },
  heroScore: {
    minWidth: 74,
    borderRadius: 18,
    paddingVertical: 10,
    paddingHorizontal: 12,
    backgroundColor: 'rgba(255,255,255,0.18)',
    alignItems: 'center',
  },
  heroScoreValue: {
    color: '#fff',
    fontSize: 21,
    fontWeight: '900',
  },
  heroScoreLabel: {
    color: 'rgba(255,255,255,0.75)',
    fontSize: 10,
    fontWeight: '700',
  },
  heroMetaRow: {
    flexDirection: 'row',
    gap: 10,
  },
  heroMetaPill: {
    flex: 1,
    backgroundColor: 'rgba(255,255,255,0.14)',
    borderRadius: 16,
    padding: 12,
  },
  heroMetaValue: {
    color: '#fff',
    fontSize: 17,
    fontWeight: '900',
  },
  heroMetaLabel: {
    color: 'rgba(255,255,255,0.74)',
    fontSize: 11,
    fontWeight: '700',
    marginTop: 2,
  },
  pageHero: {
    backgroundColor: C.card,
    borderRadius: 24,
    padding: 18,
    gap: 4,
    borderWidth: 1,
    borderColor: C.border,
    shadowColor: '#000',
    shadowOpacity: 0.05,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 8 },
    elevation: 3,
  },
  pageHeroTitle: {
    color: C.ink,
    fontSize: 23,
    fontWeight: '900',
  },
  pageHeroText: {
    color: C.muted,
    fontSize: 13,
    lineHeight: 19,
  },
  card: {
    backgroundColor: C.card,
    borderRadius: 18,
    padding: 16,
    gap: 12,
    borderWidth: 1,
    borderColor: C.border,
    shadowColor: '#000',
    shadowOpacity: 0.04,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },
    elevation: 2,
  },
  formCard: {
    backgroundColor: C.card,
    borderRadius: 22,
    padding: 18,
    gap: 12,
    borderWidth: 1,
    borderColor: C.border,
    shadowColor: '#000',
    shadowOpacity: 0.05,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 8 },
    elevation: 3,
  },
  inactiveCard: {
    opacity: 0.62,
  },
  progressCard: {
    backgroundColor: C.card,
    borderRadius: 22,
    padding: 18,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
    borderWidth: 1,
    borderColor: C.border,
    shadowColor: '#000',
    shadowOpacity: 0.06,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 8 },
    elevation: 4,
  },
  progressCircle: {
    width: 78,
    height: 78,
    borderRadius: 39,
    backgroundColor: C.primaryLight,
    borderWidth: 8,
    borderColor: C.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  progressText: {
    color: C.ink,
    fontSize: 17,
    fontWeight: '800',
  },
  progressTrack: {
    height: 8,
    backgroundColor: C.primaryLight,
    borderRadius: 8,
    overflow: 'hidden',
    marginTop: 8,
  },
  progressFill: {
    height: '100%',
    backgroundColor: C.primary,
    borderRadius: 8,
  },
  quickStatsRow: {
    flexDirection: 'row',
    gap: 10,
  },
  miniMetric: {
    flex: 1,
    backgroundColor: C.card,
    borderRadius: 18,
    paddingVertical: 12,
    paddingHorizontal: 10,
    borderWidth: 1,
    borderColor: C.border,
  },
  miniMetricValue: {
    color: C.ink,
    fontSize: 20,
    fontWeight: '900',
  },
  miniMetricLabel: {
    color: C.muted,
    fontSize: 11,
    fontWeight: '700',
    marginTop: 2,
  },
  weekCard: {
    backgroundColor: C.card,
    borderRadius: 22,
    padding: 16,
    gap: 14,
    borderWidth: 1,
    borderColor: C.border,
    shadowColor: '#000',
    shadowOpacity: 0.04,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 6 },
    elevation: 2,
  },
  weekHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  weekRow: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    justifyContent: 'space-between',
    gap: 8,
    minHeight: 104,
  },
  weekDay: {
    flex: 1,
    alignItems: 'center',
    gap: 8,
  },
  weekBarTrack: {
    width: '100%',
    height: 72,
    borderRadius: 12,
    backgroundColor: C.primaryLight,
    overflow: 'hidden',
    justifyContent: 'flex-end',
  },
  weekBarFill: {
    width: '100%',
    borderRadius: 12,
    backgroundColor: C.primary,
  },
  weekDayText: {
    color: C.muted,
    fontSize: 10,
    fontWeight: '800',
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 4,
  },
  sectionTitle: {
    color: C.ink,
    fontSize: 17,
    fontWeight: '800',
  },
  linkText: {
    color: C.primary,
    fontSize: 14,
    fontWeight: '700',
  },
  label: {
    color: C.ink,
    fontSize: 13,
    fontWeight: '700',
  },
  input: {
    minHeight: 52,
    borderRadius: 14,
    backgroundColor: '#F6F7F9',
    color: C.ink,
    paddingHorizontal: 14,
    fontSize: 15,
    borderWidth: 1,
    borderColor: 'transparent',
  },
  quickTargetRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  primaryButton: {
    minHeight: 52,
    borderRadius: 16,
    backgroundColor: C.primary,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 16,
    shadowColor: C.primaryDark,
    shadowOpacity: 0.18,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },
    elevation: 3,
  },
  primaryButtonText: {
    color: '#fff',
    fontSize: 15,
    fontWeight: '800',
  },
  secondaryButton: {
    minHeight: 52,
    borderRadius: 16,
    backgroundColor: C.redLight,
    alignItems: 'center',
    justifyContent: 'center',
  },
  secondaryButtonText: {
    color: C.red,
    fontSize: 15,
    fontWeight: '800',
  },
  disabledButton: {
    opacity: 0.45,
  },
  pressed: {
    transform: [{ scale: 0.98 }],
  },
  muted: {
    color: C.muted,
    fontSize: 13,
    lineHeight: 19,
  },
  mutedText: {
    color: C.muted,
  },
  emptyCard: {
    backgroundColor: C.card,
    borderRadius: 22,
    padding: 26,
    alignItems: 'center',
    gap: 12,
    borderWidth: 1,
    borderColor: C.border,
    shadowColor: '#000',
    shadowOpacity: 0.04,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 6 },
    elevation: 2,
  },
  emptyIcon: {
    width: 58,
    height: 58,
    borderRadius: 20,
    backgroundColor: C.primaryLight,
    alignItems: 'center',
    justifyContent: 'center',
  },
  emptyIconText: {
    color: C.primary,
    fontSize: 34,
    lineHeight: 36,
    fontWeight: '900',
  },
  emptyTitle: {
    color: C.ink,
    fontSize: 18,
    fontWeight: '800',
  },
  emptyText: {
    color: C.muted,
    fontSize: 14,
    lineHeight: 21,
    textAlign: 'center',
    marginBottom: 6,
  },
  habitHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  habitMainPress: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  habitTaskCard: {
    backgroundColor: C.card,
    borderRadius: 22,
    padding: 16,
    paddingLeft: 18,
    gap: 12,
    borderWidth: 1,
    borderColor: C.border,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOpacity: 0.05,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 7 },
    elevation: 3,
  },
  habitListCard: {
    backgroundColor: C.card,
    borderRadius: 22,
    padding: 16,
    paddingLeft: 18,
    gap: 12,
    borderWidth: 1,
    borderColor: C.border,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOpacity: 0.04,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 6 },
    elevation: 2,
  },
  habitColorRail: {
    position: 'absolute',
    left: 0,
    top: 0,
    bottom: 0,
    width: 5,
  },
  habitIcon: {
    width: 48,
    height: 48,
    borderRadius: 16,
    backgroundColor: C.primaryLight,
    alignItems: 'center',
    justifyContent: 'center',
  },
  habitIconText: {
    color: C.primary,
    fontSize: 20,
    fontWeight: '800',
  },
  habitName: {
    color: C.ink,
    fontSize: 16,
    fontWeight: '800',
  },
  habitMetaRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 10,
    backgroundColor: C.bgSoft,
    borderRadius: 14,
    paddingHorizontal: 12,
    paddingVertical: 9,
  },
  habitMetaText: {
    color: C.muted,
    fontSize: 12,
    fontWeight: '700',
  },
  habitActions: {
    alignItems: 'flex-end',
    gap: 6,
  },
  statusLine: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  statusPill: {
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  statusText: {
    fontSize: 11,
    fontWeight: '800',
  },
  checkRow: {
    flexDirection: 'row',
    gap: 8,
  },
  logPreview: {
    backgroundColor: C.bgSoft,
    borderRadius: 14,
    padding: 12,
    gap: 4,
  },
  logPreviewText: {
    color: C.ink,
    fontSize: 12,
    fontWeight: '800',
  },
  logPreviewNote: {
    color: C.muted,
    fontSize: 12,
    lineHeight: 18,
  },
  actionButton: {
    flex: 1,
    minHeight: 40,
    borderRadius: 13,
    alignItems: 'center',
    justifyContent: 'center',
  },
  actionText: {
    fontSize: 12,
    fontWeight: '800',
  },
  successSoft: { backgroundColor: C.primaryLight },
  dangerSoft: { backgroundColor: C.redLight },
  warnSoft: { backgroundColor: C.orangeLight },
  neutralSoft: { backgroundColor: '#EEF0EE' },
  successText: { color: C.primary },
  dangerText: { color: C.red },
  warnText: { color: C.orange },
  smallButton: {
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
    backgroundColor: '#EEF0EE',
  },
  smallButtonText: {
    color: C.ink,
    fontSize: 12,
    fontWeight: '800',
  },
  chipWrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  chip: {
    paddingHorizontal: 14,
    paddingVertical: 9,
    borderRadius: 999,
    backgroundColor: '#EEF0EE',
  },
  chipActive: {
    backgroundColor: C.primaryLight,
  },
  chipText: {
    color: C.muted,
    fontSize: 13,
    fontWeight: '700',
  },
  chipTextActive: {
    color: C.primary,
  },
  colorRow: {
    flexDirection: 'row',
    gap: 10,
  },
  colorSwatch: {
    width: 38,
    height: 38,
    borderRadius: 14,
    borderWidth: 3,
    borderColor: 'transparent',
  },
  colorSwatchActive: {
    borderColor: C.ink,
    transform: [{ scale: 1.04 }],
  },
  dayRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 6,
  },
  dayChip: {
    flex: 1,
    minHeight: 42,
    borderRadius: 13,
    backgroundColor: '#EEF0EE',
    alignItems: 'center',
    justifyContent: 'center',
  },
  dayChipActive: {
    backgroundColor: C.primary,
  },
  dayText: {
    color: C.muted,
    fontSize: 12,
    fontWeight: '800',
  },
  dayTextActive: {
    color: '#fff',
  },
  statsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  statCard: {
    width: '48%',
    backgroundColor: C.card,
    borderRadius: 18,
    padding: 16,
    borderWidth: 1,
    borderColor: C.border,
    gap: 6,
  },
  statValue: {
    color: C.ink,
    fontSize: 24,
    fontWeight: '800',
  },
  logRow: {
    minHeight: 42,
    borderRadius: 14,
    backgroundColor: C.bgSoft,
    paddingHorizontal: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  logValue: {
    color: C.ink,
    fontSize: 16,
    fontWeight: '900',
  },
  logDate: {
    color: C.ink,
    fontSize: 13,
    fontWeight: '900',
  },
  calendarCard: {
    backgroundColor: C.card,
    borderRadius: 24,
    padding: 16,
    gap: 14,
    borderWidth: 1,
    borderColor: C.border,
    shadowColor: '#000',
    shadowOpacity: 0.05,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 8 },
    elevation: 3,
  },
  calendarWeekdays: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  calendarWeekday: {
    width: `${100 / 7}%`,
    textAlign: 'center',
    color: C.muted,
    fontSize: 11,
    fontWeight: '900',
  },
  calendarGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    rowGap: 8,
  },
  calendarDay: {
    width: `${100 / 7}%`,
    minHeight: 44,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
    borderRadius: 14,
  },
  calendarDaySelected: {
    backgroundColor: C.primaryLight,
  },
  calendarDayMuted: {
    opacity: 0.35,
  },
  calendarDayText: {
    color: C.ink,
    fontSize: 13,
    fontWeight: '900',
  },
  calendarDayTextSelected: {
    color: C.primaryDark,
  },
  calendarDot: {
    width: 6,
    height: 6,
    borderRadius: 999,
  },
  calendarDone: {
    backgroundColor: C.primary,
  },
  calendarPartial: {
    backgroundColor: C.orange,
  },
  calendarMissed: {
    backgroundColor: C.red,
  },
  calendarFuture: {
    backgroundColor: C.faint,
  },
  calendarNone: {
    backgroundColor: 'transparent',
  },
  calendarLegend: {
    flexDirection: 'row',
    gap: 12,
    flexWrap: 'wrap',
  },
  legendItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  legendDot: {
    width: 8,
    height: 8,
    borderRadius: 999,
  },
  legendText: {
    color: C.muted,
    fontSize: 11,
    fontWeight: '700',
  },
  calendarHabitCard: {
    backgroundColor: C.card,
    borderRadius: 20,
    padding: 14,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    borderWidth: 1,
    borderColor: C.border,
  },
  detailHero: {
    borderRadius: 28,
    padding: 22,
    gap: 16,
    shadowColor: '#000',
    shadowOpacity: 0.16,
    shadowRadius: 20,
    shadowOffset: { width: 0, height: 10 },
    elevation: 7,
  },
  detailCategory: {
    color: 'rgba(255,255,255,0.74)',
    fontSize: 12,
    fontWeight: '800',
  },
  detailTitle: {
    color: '#fff',
    fontSize: 25,
    fontWeight: '900',
    marginTop: 2,
  },
  detailText: {
    color: 'rgba(255,255,255,0.84)',
    fontSize: 13,
    lineHeight: 19,
    marginTop: 4,
  },
  detailActions: {
    flexDirection: 'row',
    gap: 10,
  },
  detailActionButton: {
    flex: 1,
  },
  detailSmallAction: {
    minHeight: 52,
    minWidth: 88,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 16,
  },
  profileCard: {
    backgroundColor: C.primary,
    borderRadius: 24,
    padding: 18,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
    shadowColor: C.primaryDark,
    shadowOpacity: 0.18,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 9 },
    elevation: 5,
  },
  avatar: {
    width: 62,
    height: 62,
    borderRadius: 20,
    backgroundColor: 'rgba(255,255,255,0.22)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarText: {
    color: '#fff',
    fontSize: 26,
    fontWeight: '800',
  },
  profileName: {
    color: '#fff',
    fontSize: 19,
    fontWeight: '800',
  },
  profileSub: {
    color: 'rgba(255,255,255,0.78)',
    fontSize: 13,
    marginTop: 2,
  },
  profileStatsRow: {
    flexDirection: 'row',
    gap: 10,
  },
  modalBackdrop: {
    flex: 1,
    justifyContent: 'flex-end',
  },
  modalDim: {
    ...StyleSheet.absoluteFill,
    backgroundColor: 'rgba(28,32,53,0.36)',
  },
  sheetWrap: {
    justifyContent: 'flex-end',
  },
  checkSheet: {
    backgroundColor: C.card,
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    paddingHorizontal: 18,
    paddingTop: 10,
    gap: 14,
    shadowColor: '#000',
    shadowOpacity: 0.16,
    shadowRadius: 24,
    shadowOffset: { width: 0, height: -10 },
    elevation: 14,
  },
  sheetHandle: {
    alignSelf: 'center',
    width: 42,
    height: 5,
    borderRadius: 999,
    backgroundColor: '#DCE1E0',
    marginBottom: 4,
  },
  sheetHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  sheetTitle: {
    color: C.ink,
    fontSize: 18,
    fontWeight: '900',
  },
  statusSegment: {
    flexDirection: 'row',
    gap: 8,
    backgroundColor: C.bgSoft,
    borderRadius: 18,
    padding: 6,
  },
  statusChoice: {
    flex: 1,
    minHeight: 40,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 14,
  },
  statusChoiceActive: {
    backgroundColor: C.card,
    shadowColor: '#000',
    shadowOpacity: 0.05,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
    elevation: 2,
  },
  statusChoiceText: {
    color: C.muted,
    fontSize: 12,
    fontWeight: '900',
  },
  sheetFieldRow: {
    flexDirection: 'row',
    gap: 12,
  },
  sheetField: {
    flex: 1,
    gap: 8,
  },
  moodRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
  },
  noteInput: {
    minHeight: 86,
    paddingTop: 12,
    textAlignVertical: 'top',
  },
  tabBar: {
    position: 'absolute',
    left: 12,
    right: 12,
    bottom: 10,
    backgroundColor: C.card,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: C.border,
    flexDirection: 'row',
    paddingTop: 8,
    paddingHorizontal: 8,
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowRadius: 20,
    shadowOffset: { width: 0, height: 8 },
    elevation: 8,
  },
  tabButton: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 40,
    borderRadius: 18,
    paddingHorizontal: 4,
    paddingVertical: 8,
  },
  tabButtonActive: {
    backgroundColor: C.primaryLight,
  },
  tabText: {
    color: C.muted,
    fontSize: 12,
    fontWeight: '800',
  },
  tabTextActive: {
    color: C.primary,
  },
  fab: {
    position: 'absolute',
    right: 20,
    width: 58,
    height: 58,
    borderRadius: 20,
    backgroundColor: C.primary,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: C.primaryDark,
    shadowOpacity: 0.32,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 8 },
    elevation: 9,
  },
  fabText: {
    color: '#fff',
    fontSize: 34,
    lineHeight: 36,
    fontWeight: '900',
  },
  appRoot: {
    backgroundColor: C.bg,
  },
  heroProgressTrack: {
    height: 9,
    borderRadius: 999,
    backgroundColor: 'rgba(255,255,255,0.22)',
    overflow: 'hidden',
  },
  heroProgressFill: {
    height: '100%',
    borderRadius: 999,
    backgroundColor: '#fff',
  },
  motivationCard: {
    backgroundColor: 'rgba(255,255,255,0.14)',
    borderRadius: 20,
    padding: 14,
    gap: 7,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.12)',
  },
  motivationHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  motivationTag: {
    color: '#fff',
    fontSize: 11,
    fontWeight: '900',
    backgroundColor: 'rgba(255,255,255,0.18)',
    borderRadius: 999,
    paddingHorizontal: 9,
    paddingVertical: 4,
    overflow: 'hidden',
  },
  motivationCount: {
    color: 'rgba(255,255,255,0.72)',
    fontSize: 11,
    fontWeight: '800',
  },
  motivationTitle: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '900',
    lineHeight: 21,
  },
  motivationText: {
    color: 'rgba(255,255,255,0.82)',
    fontSize: 13,
    lineHeight: 19,
  },
  motivationControls: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
    paddingTop: 2,
  },
  motivationNavButton: {
    width: 34,
    height: 30,
    borderRadius: 12,
    backgroundColor: 'rgba(255,255,255,0.16)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  motivationNavText: {
    color: '#fff',
    fontSize: 17,
    lineHeight: 19,
    fontWeight: '900',
  },
  motivationDots: {
    flexDirection: 'row',
    gap: 6,
    flex: 1,
    justifyContent: 'center',
  },
  motivationDot: {
    width: 18,
    height: 5,
    borderRadius: 999,
    backgroundColor: 'rgba(255,255,255,0.26)',
  },
  motivationDotActive: {
    width: 30,
    backgroundColor: '#fff',
  },
  formPreviewCard: {
    backgroundColor: C.card,
    borderRadius: 22,
    padding: 16,
    paddingLeft: 18,
    gap: 12,
    borderWidth: 1.5,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOpacity: 0.05,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 8 },
    elevation: 3,
  },
  formSectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  formStep: {
    color: C.muted,
    fontSize: 12,
    fontWeight: '900',
    backgroundColor: C.bgSoft,
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  formHint: {
    color: C.muted,
    fontSize: 12,
    lineHeight: 18,
    textAlign: 'center',
    paddingHorizontal: 10,
  },
  inputDisabled: {
    color: C.faint,
    backgroundColor: '#EEF0EE',
  },
  sheetContextCard: {
    backgroundColor: C.bgSoft,
    borderRadius: 18,
    padding: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  sheetContextLabel: {
    color: C.ink,
    fontSize: 13,
    fontWeight: '900',
  },
  sheetContextText: {
    color: C.muted,
    fontSize: 12,
    fontWeight: '700',
    marginTop: 2,
  },
  sheetHint: {
    color: C.muted,
    fontSize: 12,
    lineHeight: 18,
  },
  sheetCancelButton: {
    minHeight: 44,
    borderRadius: 15,
    backgroundColor: C.bgSoft,
    alignItems: 'center',
    justifyContent: 'center',
  },
  sheetCancelText: {
    color: C.muted,
    fontSize: 14,
    fontWeight: '900',
  },
  compactPercent: {
    minWidth: 58,
    height: 42,
    borderRadius: 16,
    backgroundColor: C.primaryLight,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 10,
  },
  compactPercentText: {
    color: C.primaryDark,
    fontSize: 17,
    fontWeight: '900',
  },
  compactMetricRow: {
    flexDirection: 'row',
    gap: 8,
  },
  todaySummaryCard: {
    backgroundColor: C.card,
    borderRadius: 22,
    padding: 16,
    gap: 12,
    borderWidth: 1,
    borderColor: C.border,
    shadowColor: '#000',
    shadowOpacity: 0.05,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 7 },
    elevation: 3,
  },
  todaySummaryTop: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  todayTasksList: {
    gap: 10,
  },
  todayWeekCard: {
    backgroundColor: C.card,
    borderRadius: 22,
    padding: 14,
    gap: 12,
    borderWidth: 1,
    borderColor: C.border,
    shadowColor: '#000',
    shadowOpacity: 0.04,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 5 },
    elevation: 2,
  },
  todayWeekRow: {
    flexDirection: 'row',
    alignItems: 'stretch',
    justifyContent: 'space-between',
    gap: 8,
    minHeight: 92,
  },
  todayWeekBarTrack: {
    width: '100%',
    height: 48,
    borderRadius: 10,
    backgroundColor: C.primaryLight,
    overflow: 'hidden',
    justifyContent: 'flex-end',
    borderWidth: 1,
    borderColor: 'transparent',
  },
  todayWeekBarTrackToday: {
    borderColor: C.primary,
  },
  weekSummaryPill: {
    minWidth: 58,
    borderRadius: 999,
    backgroundColor: C.primaryLight,
    paddingHorizontal: 10,
    paddingVertical: 6,
    alignItems: 'center',
  },
  weekSummaryText: {
    color: C.primaryDark,
    fontSize: 12,
    fontWeight: '900',
  },
  weekProgressTrack: {
    height: 7,
    borderRadius: 999,
    backgroundColor: C.bgSoft,
    overflow: 'hidden',
  },
  weekProgressFill: {
    height: '100%',
    borderRadius: 999,
    backgroundColor: C.primary,
  },
  weekDayToday: {
    backgroundColor: C.bgSoft,
  },
  weekDayTextToday: {
    color: C.primaryDark,
  },
  weekDayCount: {
    color: C.muted,
    fontSize: 10,
    fontWeight: '900',
  },
  weekDayCountToday: {
    color: C.ink,
  },
  weekLegendRow: {
    flexDirection: 'row',
    gap: 12,
    flexWrap: 'wrap',
  },
  rhythmDone: {
    backgroundColor: C.primary,
  },
  rhythmPartial: {
    backgroundColor: C.orange,
  },
  rhythmMissed: {
    backgroundColor: C.red,
  },
  rhythmFuture: {
    backgroundColor: C.faint,
  },
  rhythmNone: {
    backgroundColor: 'transparent',
  },
  habitsHero: {
    backgroundColor: C.card,
    borderRadius: 24,
    padding: 16,
    gap: 14,
    borderWidth: 1,
    borderColor: C.border,
    shadowColor: '#000',
    shadowOpacity: 0.05,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 8 },
    elevation: 3,
  },
  habitsHeroTop: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  habitsSummaryRow: {
    flexDirection: 'row',
    gap: 8,
  },
  heroAddButton: {
    width: 46,
    height: 46,
    borderRadius: 16,
    backgroundColor: C.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  heroAddText: {
    color: '#fff',
    fontSize: 28,
    lineHeight: 30,
    fontWeight: '900',
  },
  filterRow: {
    flexDirection: 'row',
    gap: 8,
  },
  filterChip: {
    flex: 1,
    minHeight: 42,
    borderRadius: 15,
    backgroundColor: C.card,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: C.border,
    paddingHorizontal: 4,
  },
  filterChipActive: {
    backgroundColor: C.primary,
    borderColor: C.primary,
  },
  filterChipText: {
    color: C.muted,
    fontSize: 12,
    fontWeight: '900',
    textAlign: 'center',
  },
  filterChipTextActive: {
    color: '#fff',
  },
  habitTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  habitProgressRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  habitProgressText: {
    flexDirection: 'row',
    gap: 10,
    flexShrink: 1,
  },
  habitPercent: {
    color: C.ink,
    fontSize: 14,
    fontWeight: '900',
  },
  habitActionRow: {
    flexDirection: 'row',
    gap: 8,
  },
  actionGhostButton: {
    flex: 1,
    minHeight: 38,
    borderRadius: 13,
    backgroundColor: C.bgSoft,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 6,
  },
  actionGhostText: {
    color: C.ink,
    fontSize: 12,
    fontWeight: '900',
    textAlign: 'center',
  },
  habitStatusPanel: {
    backgroundColor: C.bgSoft,
    borderRadius: 16,
    padding: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  habitStatusDot: {
    width: 12,
    height: 12,
    borderRadius: 999,
  },
  habitStatusLabel: {
    color: C.ink,
    fontSize: 12,
    fontWeight: '900',
  },
  habitStatusText: {
    color: C.muted,
    fontSize: 12,
    lineHeight: 17,
    marginTop: 2,
  },
  habitMiniGrid: {
    flexDirection: 'row',
    gap: 8,
  },
  habitMiniPill: {
    flex: 1,
    backgroundColor: C.bgSoft,
    borderRadius: 14,
    paddingHorizontal: 11,
    paddingVertical: 9,
  },
  habitMiniLabel: {
    color: C.muted,
    fontSize: 10,
    fontWeight: '800',
  },
  habitMiniValue: {
    color: C.ink,
    fontSize: 12,
    fontWeight: '900',
    marginTop: 2,
  },
  habitCardActions: {
    flexDirection: 'row',
    gap: 10,
  },
  habitDoneButton: {
    flex: 1,
    minHeight: 46,
    borderRadius: 15,
    backgroundColor: C.primary,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 12,
    shadowColor: C.primaryDark,
    shadowOpacity: 0.14,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 5 },
    elevation: 2,
  },
  habitDoneButtonActive: {
    backgroundColor: C.primaryDark,
  },
  habitDoneButtonText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: '900',
  },
  habitDoneButtonTextActive: {
    color: '#fff',
  },
  habitStateButton: {
    minWidth: 82,
    minHeight: 46,
    borderRadius: 15,
    backgroundColor: C.bgSoft,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 12,
    borderWidth: 1,
    borderColor: C.border,
  },
  habitStateButtonText: {
    color: C.ink,
    fontSize: 13,
    fontWeight: '900',
  },
  statsHero: {
    backgroundColor: C.card,
    borderRadius: 24,
    padding: 16,
    gap: 14,
    borderWidth: 1,
    borderColor: C.border,
  },
  statsChartCard: {
    backgroundColor: C.card,
    borderRadius: 22,
    padding: 16,
    gap: 14,
    borderWidth: 1,
    borderColor: C.border,
  },
  statsBreakdownCard: {
    backgroundColor: C.card,
    borderRadius: 22,
    padding: 16,
    gap: 12,
    borderWidth: 1,
    borderColor: C.border,
  },
  breakdownRow: {
    gap: 8,
  },
  breakdownLabel: {
    color: C.ink,
    fontSize: 13,
    fontWeight: '800',
  },
  breakdownValue: {
    color: C.muted,
    fontSize: 12,
    fontWeight: '800',
  },
  breakdownTrack: {
    height: 9,
    borderRadius: 999,
    backgroundColor: C.bgSoft,
    overflow: 'hidden',
  },
  breakdownFill: {
    height: '100%',
    borderRadius: 999,
  },
  breakdownSuccess: {
    backgroundColor: C.primary,
  },
  breakdownDanger: {
    backgroundColor: C.red,
  },
  breakdownWarn: {
    backgroundColor: C.orange,
  },
  topHabitRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    backgroundColor: C.bgSoft,
    borderRadius: 16,
    padding: 10,
  },
  topHabitRank: {
    width: 24,
    color: C.primaryDark,
    fontSize: 16,
    fontWeight: '900',
    textAlign: 'center',
  },
  activityRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    backgroundColor: C.bgSoft,
    borderRadius: 16,
    padding: 10,
  },
  activityDot: {
    width: 10,
    height: 10,
    borderRadius: 999,
  },
  calendarHero: {
    backgroundColor: C.card,
    borderRadius: 24,
    padding: 16,
    gap: 14,
    borderWidth: 1,
    borderColor: C.border,
  },
  calendarHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  calendarHeaderCenter: {
    flex: 1,
    alignItems: 'center',
  },
  calendarNavButton: {
    width: 40,
    height: 40,
    borderRadius: 14,
    backgroundColor: C.bgSoft,
    alignItems: 'center',
    justifyContent: 'center',
  },
  calendarNavText: {
    color: C.ink,
    fontSize: 19,
    lineHeight: 21,
    fontWeight: '900',
  },
  calendarToday: {
    borderWidth: 1,
    borderColor: C.primary,
  },
  calendarTinyText: {
    color: C.muted,
    fontSize: 9,
    fontWeight: '800',
  },
  selectedDayCard: {
    backgroundColor: C.card,
    borderRadius: 22,
    padding: 16,
    gap: 12,
    borderWidth: 1,
    borderColor: C.border,
  },
  detailHeroTrack: {
    height: 8,
    borderRadius: 999,
    backgroundColor: 'rgba(255,255,255,0.24)',
    overflow: 'hidden',
  },
  detailHeroFill: {
    height: '100%',
    borderRadius: 999,
    backgroundColor: '#fff',
  },
  detailTodayCard: {
    backgroundColor: C.card,
    borderRadius: 22,
    padding: 16,
    gap: 12,
    borderWidth: 1,
    borderColor: C.border,
  },
  detailLastLog: {
    backgroundColor: C.bgSoft,
    borderRadius: 16,
    padding: 12,
    gap: 4,
  },
  detailHistoryCard: {
    backgroundColor: C.card,
    borderRadius: 22,
    padding: 16,
    gap: 14,
    borderWidth: 1,
    borderColor: C.border,
  },
  historyGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  historyItem: {
    width: 34,
    alignItems: 'center',
    gap: 5,
  },
  historyDot: {
    width: 24,
    height: 24,
    borderRadius: 9,
    borderWidth: 1,
    borderColor: 'transparent',
  },
  historyDotToday: {
    borderColor: C.ink,
  },
  historyDayText: {
    color: C.muted,
    fontSize: 9,
    fontWeight: '800',
  },
  historyDone: {
    backgroundColor: C.primary,
  },
  historyMissed: {
    backgroundColor: C.red,
  },
  historySkipped: {
    backgroundColor: C.orange,
  },
  historyPending: {
    backgroundColor: C.faint,
  },
  historyOff: {
    backgroundColor: C.bgSoft,
    borderColor: C.border,
  },
  detailControlRow: {
    flexDirection: 'row',
    gap: 10,
  },
  detailControlButton: {
    flex: 1,
    minHeight: 48,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 10,
  },
  detailControlText: {
    fontSize: 13,
    fontWeight: '900',
    textAlign: 'center',
  },
  profileHero: {
    backgroundColor: C.primary,
    borderRadius: 26,
    padding: 18,
    gap: 16,
  },
  profileHeroTop: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
  },
  profileBadge: {
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
    backgroundColor: 'rgba(255,255,255,0.18)',
  },
  profileBadgeText: {
    color: '#fff',
    fontSize: 11,
    fontWeight: '900',
  },
  profileHeroStats: {
    flexDirection: 'row',
    gap: 8,
  },
  profileRow: {
    minHeight: 46,
    borderRadius: 14,
    backgroundColor: C.bgSoft,
    paddingHorizontal: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  profileRowLabel: {
    color: C.muted,
    fontSize: 13,
    fontWeight: '800',
  },
  profileRowValue: {
    color: C.ink,
    fontSize: 13,
    fontWeight: '900',
    flexShrink: 1,
    textAlign: 'right',
  },
  profileNotice: {
    backgroundColor: C.primaryLight,
    borderRadius: 20,
    padding: 16,
    gap: 5,
    borderWidth: 1,
    borderColor: 'rgba(60,184,120,0.14)',
  },
  profileNoticeTitle: {
    color: C.primaryDark,
    fontSize: 15,
    fontWeight: '900',
  },
  profileNoticeText: {
    color: C.primaryDark,
    fontSize: 13,
    lineHeight: 19,
  },
});

